# Backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;

vsync = true;
use-damage = true;

# Opacity 
active-opacity = 1;
inactive-opacity = 1;

opacity-rule = [
  "90:class_g = 'Alacritty' && focused",
  "70:class_g = 'Alacritty' && !focused"
]

blur-background = true
blur-background-exclude = [
  "window_type = 'dock'",
  "class_g = 'i3-frame'"
]
blur-method = "dual_kawase";
blur-strength = 8;

# Rounded corners
corner-radius = 15

rounded-corners-exclude = [
  "class_g = 'Polybar'"
];

# Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Frame
frame-opacity = 0.0

# Misc safety
detect-client-opacity = true;
detect-transient = true;
detect-rounded-corners = true;

